#[Info]
site_name: HYOI wiki   #网站名字
site_description: We are HYOIer.
site_author: HYOI #作者名
site_url: https://lav2.top/wiki/  #网站地址
# copyright: Copyright &copy; 2023 leoalasiaga # 左下角的版权声明

# [Navigtion]
nav:
  - 简介: index.md
  - 语言基础:
    - c++基础: 语言基础/cpp.md
  - 游记:
    - LA:
      - 游记test: 游记/LA/游记test.md
    - Rubbish_Du:
      - 2024CSP-S 游寄: 游记/Rubbish_Du/2024CSP-S游寄.md
      - 2024OIFHA游记: 游记/Rubbish_Du/2024OIFHA游记.md
  - 闲话:
    - LA:
      - 鲜花01: 闲话/LA/鲜花01.md
#[UI]
# Theme
theme:
  name: null
  custom_dir: 'mkdocs-material/material/templates'
  static_templates:
    - 404.html
  language: 'zh'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  favicon: 'favicon.ico'
  icon:
    logo: 'material/school'
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.instant
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

plugins: []
     
hooks:
  - hooks/on_env.py

# Customization
# extra:
#   disqus: 'OI-Wiki'
#   copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'
#   pagetime: 'on'
#   manifest: 'manifest.webmanifest'
#   githash: ''
#   analytics:
#     provider: google
#     property: UA-124485594-1

extra_javascript:
  - '_static/js/math-csr.js?math-csr'
  - 'assets/vendor/mathjax/es5/tex-mml-chtml.js?math-csr'
  - '{OIWikiFeedbackSystemFrontendJS}' # see: scripts/pre-build/install-feedback-sys-frontend.ts
  - '{OIWikiFeedbackSystemFrontendContentScript}' # see: scripts/pre-build/install-feedback-sys-frontend.ts
  # - '_static/js/mathjax.js'
  # - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # - '_static/js/tex-mml-chtml.js'
  - _static/js/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - '_static/css/extra.css?v=16'
  # - '_static/css/offset-inject-debug.css'
  - '{OIWikiFeedbackSystemFrontendCSS}' # see: scripts/pre-build/install-feedback-sys-frontend.ts
  - https://unpkg.com/katex@0/dist/katex.min.css
# Extensions
markdown_extensions:
  # - document-offsets-injection:
      # debug: true
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true