#[Info]
site_name: HYOI wiki   #网站名字
site_description: 邯郸市第一中学算法竞赛wiki
site_author: HYOI #作者名
site_url: https://lav2.top/  #网站地址
# copyright: Copyright &copy; 2023 leoalasiaga # 左下角的版权声明

# [Navigtion]
nav:
  - 简介: index.md
  - 语言基础:
    - c++基础: 语言基础/c++基础.md
    - 环境配置: 语言基础/环境配置.md
    - 常见容器及其常用函数: 语言基础/常见容器及其常用函数.md
    - 渐进时间复杂度: 语言基础/渐进时间复杂度.md
  - 基础算法:
    - 前缀和与差分: 基础算法/前缀和与差分.md
    - 深度优先搜索: 基础算法/深度优先搜索.md
    - 广度优先搜索: 基础算法/广度优先搜索.md
    - 贪心: 基础算法/贪心.md
  - 数据结构:
    - st表: 数据结构/st表.md
    - 并查集: 数据结构/并查集.md
    - 树状数组: 数据结构/树状数组.md
    - 线段树: 数据结构/线段树.md
  - 图论:
    - 树上差分: 图论/树上差分.md
    - 树的直径: 图论/树的直径.md
    - 树链剖分: 图论/树链剖分.md
    - 静态点分治: 图论/静态点分治.md
  - 组合数学:
    - 简介: 组合数学/简介.md
    - 组合基础: 组合数学/组合基础.md
  - 其它数学:
    - 概率论: 其它数学/概率论.md
  - OI无关: 
    - 如何用C++奏响《东方红》: OI无关/如何用C++奏响《东方红》.md 
  - 游记:
    - LA:
      - NOI2024退役记: 游记/LA/NOI2024退役记.md
      - 联合省选2024游记: 游记/LA/联合省选2024游记.md
    - Rubbish_Du:
      - 2024CSP-S 游寄: 游记/Rubbish_Du/2024CSP-S游寄.md
      - 2024OIFHA游记: 游记/Rubbish_Du/2024OIFHA游记.md
      - THUPC 2025 游玩记: 游记/Rubbish_Du/THUPC 2025 游玩记.md
      - 2024NOIP游记: 游记/Rubbish_Du/2024NOIP游记.md
    - qwerty111111:
      - 中山一周行: 游记/qwerty111111/中山一周行.md
    - loynyng_fasfy:
      - CSP-S 2024 游记: 游记/loynyng_fasfy/CSP-S2024游记.md
    - dtbigwaves:
      - CSP-S 2024游记: 游记/dtbigwaves/CSP-S 2024游记.md
      - NOIp 2024游记: 游记/dtbigwaves/NOIp 2024游记.md
    - KccoT:
      - csp s 游记: 游记/KccoT/csps游记.md
    - caw0218:
      - CSP-S 2024 游记: 游记/caw0218/CSP-S2024游记.md
  - 闲话:
    - LA:
      - 无题: 闲话/LA/无题.md
      - Goodbye, 2024: 闲话/LA/Goodbye, 2024.md
    - Danubius:
      - 典籍里の机房一: 闲话/Danubius/典籍里の机房一.md
      - 浅谈历史研究视角: 闲话/Danubius/浅谈历史研究视角.md
    - Rubbish_Du:
      - 故事集: 闲话/Rubbish_Du/故事集.md
      - 闲话集: 闲话/Rubbish_Du/闲话集.md
      - 简单子序列相关问题: 闲话/Rubbish_Du/简单子序列相关问题.md
      - 警示后人: 闲话/Rubbish_Du/警示后人.md
    - LosTcrab:
      - 闲话——关于幸福: 闲话/LosTcrab/闲话——关于幸福.md
    - qwerty111111:
      - 机房一の恶战: 闲话/qwerty111111/机房一の恶战.md
#[UI]
# Theme
theme:
  name: null
  custom_dir: 'mkdocs-material/material/templates'
  static_templates:
    - 404.html
  language: 'zh'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  favicon: 'favicon.ico'
  icon:
    logo: 'material/school'
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.instant
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  plugins:
    - search:
        separator: '[\s\u200b\-]'

hooks:
  - hooks/on_env.py

# Customization
# extra:
#   disqus: 'OI-Wiki'
#   copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'
#   pagetime: 'on'
#   manifest: 'manifest.webmanifest'
#   githash: ''
#   analytics:
#     provider: google
#     property: UA-124485594-1

extra_javascript:
  - '_static/js/math-csr.js?math-csr'
  - 'assets/vendor/mathjax/es5/tex-mml-chtml.js?math-csr'
  # - '{OIWikiFeedbackSystemFrontendJS}' # see: scripts/pre-build/install-feedback-sys-frontend.ts
  # - '{OIWikiFeedbackSystemFrontendContentScript}' # see: scripts/pre-build/install-feedback-sys-frontend.ts
  - _static/js/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - '_static/css/extra.css?v=16'
  # - '_static/css/offset-inject-debug.css'
  - '{OIWikiFeedbackSystemFrontendCSS}' # see: scripts/pre-build/install-feedback-sys-frontend.ts
  - https://unpkg.com/katex@0/dist/katex.min.css
# Extensions
markdown_extensions:
  # - document-offsets-injection:
      # debug: true
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
